# cell settings
REPRODUCTION_CAP = 100
CELL_LIFETIME = 8_000
CELL_VISUAL_RANGE = 60

# food settings
FRICTION = 2.28
FOOD_INITIAL_MASS = 4
FOOD_MASS_GAIN = 0.18
FOOD_MAX_SPEED = 100
FOOD_VISUAL_RANGE = 70
FOOD_REPRODUCTION_THRESHHOLD = 14
FOOD_CLUSTER_STRENGTH = 0.2